from time import perf_counter
from uuid import uuid4
import os

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
import torch

from .model import GCNEncoder, FraudGAE
from .config import MODEL_SAVE_PATH, EMBEDDING_DIM, GRAPH_PT, NODE_MAPPING_PATH
from .graph_builder import build_graph
from .inference import get_fraud_score, compute_temp_embedding
from .anomaly import top_anomalies, isolate_anomalies, z_score_anomaly_scores
from .utils import load_graph, load_node_mapping

router = APIRouter()


class NewClaim(BaseModel):
    bene_sex_ident_cd: int = Field(ge=1, le=2)
    bene_race_cd: int = Field(ge=1, le=5)
    bene_esrd_ind: int = Field(ge=0, le=1)
    sp_state_code: int = Field(ge=1, le=54)
    bene_county_cd: int = Field(ge=0, le=999)
    sp_conditions: dict
    payments: dict
    provider_id: str


class PredictionRequest(BaseModel):
    claim_id: str


def _load_artifacts():
    if not os.path.exists(GRAPH_PT) or not os.path.exists(NODE_MAPPING_PATH):
        build_graph()
    data = load_graph()
    node_mapping = load_node_mapping()
    encoder = GCNEncoder(data.num_node_features, EMBEDDING_DIM)
    model = FraudGAE(encoder)
    model.load_state_dict(torch.load(MODEL_SAVE_PATH, map_location="cpu"))
    model.eval()
    return data, node_mapping, model


# These artifacts are required by all endpoints. The graph is generated by
# backend/app/graph_builder.py from the checked-in processed CSV files.
try:
    data, node_mapping, model = _load_artifacts()
except FileNotFoundError as exc:
    raise RuntimeError(
        "Graph artifact is missing. Run `python -m app.graph_builder` from the backend directory first."
    ) from exc

with torch.no_grad():
    z = model.encode(data.x, data.edge_index)


@router.get("/health")
def health():
    return {
        "status": "ok",
        "model": "GCN-based Graph Autoencoder",
        "nodes": int(data.num_nodes),
        "edges": int(data.num_edges),
        "features": int(data.num_node_features),
    }


@router.post("/submit_claim")
def submit_claim(claim: NewClaim):
    started = perf_counter()
    try:
        with torch.no_grad():
            fraud_score, top_neighbors, z_new = compute_temp_embedding(
                data=data,
                model=model,
                claim=claim.model_dump(),
                node_mapping=node_mapping,
            )
            z_all = torch.cat([model.encode(data.x, data.edge_index), z_new.unsqueeze(0)], dim=0)
            anomaly_scores = z_score_anomaly_scores(z_all)
            anomaly = anomaly_scores[-1].item()

        return {
            "claim_id": f"NEW-{uuid4().hex[:10].upper()}",
            "provider_id": claim.provider_id,
            "fraud_score": round(fraud_score, 4),
            "anomaly_score": round(anomaly, 4),
            "top_neighbors": top_neighbors,
            "model": {
                "name": "Graph Autoencoder",
                "type": "GCN + GAE",
                "features": int(data.num_node_features),
                "detection": "Embedding similarity + anomaly score",
            },
            "latency_ms": round((perf_counter() - started) * 1000, 1),
        }
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@router.post("/predict")
def predict(request: PredictionRequest):
    if request.claim_id not in node_mapping:
        raise HTTPException(status_code=404, detail="Claim ID not found in graph")
    try:
        return get_fraud_score(request.claim_id, data, z, node_mapping, num_hops=2, topk=5)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@router.get("/anomalies")
def get_anomalies(top_k: int = 10):
    indices, scores = top_anomalies(z, top_k)
    return [{"node_index": i, "score": round(s, 4)} for i, s in zip(indices, scores)]


@router.get("/isolation")
def isolation_anomaly(top_k: int = 10):
    result = isolate_anomalies(z, n_top=top_k)
    return [{"node_index": idx, "score": score} for idx, score in result]
